# 配置数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

# Freemarker 模板配置(默认)
spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefix:
    suffix: .ftl